spring:
  application:
    name: langgraph-poc
  main:
    allow-bean-definition-overriding: true
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/genai_kb}
      database: ${MONGODB_DATABASE:genai_kb}
      # Collections used:
      # - cves: CVE (Common Vulnerabilities and Exposures) data
      # - AITTechStack: AIT Tech Stack information (languages, frameworks, databases, etc.)

  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      base-url: ${OPENAI_API_BASE_URL:/v1}
      chat:
        options:
          model: ${MODEL_NAME}
          temperature: ${TEMPERATURE:0.1}
          max_tokens: ${MAX_TOKENS:512}
    # Uncomment below to use local Ollama instead of OpenAI
    # ollama:
    #   base-url: http://localhost:11434
    #   chat:
    #     options:
    #       model: qwen2.5:7b
    #       temperature: 0.0

server:
  port: 8080

logging:
  level:
    com.datanova: DEBUG
    org.bsc.langgraph4j: DEBUG
